---
title: "parse_card_statement"
author: "Jae Yeon Kim"
date: "11/4/2020"
output: html_document
---

# Install pacakges 

```{r}
if(!require(pacman)) install.packages("pacman")

pacman::p_load(tidyverse, 
               pdftools,
               tabulizer,
               lubridate, 
               purrr,
               here)

```

# Load data 

```{r}

check_statement <- extract_tables(file = here("data", "check_statement.pdf"), 
                                  method = "decide")

```

# Wrangle data 

```{r}

# Turn the list of matrices into a dataframe 
df <- map_dfr(check_statement, data.frame)

# Remove the first three rows 
df <- df %>% filter(!str_detect(X1, "TRANSACTION|transaction|DESCRIPTION|Beginning"))

# Create date column 
df <- df %>% 
    mutate(Date = map(X1, ~str_extract(., "^.{1,5}")) %>%
    map_dfr(enframe) %>%
    pull(value)
    ) 
    
# Rename columns 
names(df) <- c("Description", "Amount", "Balance", "Date")

# Reorder columns; Date comes first 
df <- df %>% relocate(Date)

# Clean date column 

## Clean 

## Fill in 

# Clean description column 

## Clean 

## Fill in 

# Clean Amount column 

## Fill in 

## Reformat 

# Clean Balance column 

## Fill in 

## Reformat 

```

```{r}
df
```


